### ISSUE TITLE
Feature Request: SGR mouse escape sequences

### ISSUE THREAD

**Issue by AdShea** [lxde/qtermwidget#100]
Is there any chance of updating to the modern sgr-style mouse sending like recent xterms (version 277 and later) send? This is xterm mouse style 1006.

This is described in the xterm documentation here:
[http://invisible-island.net/xterm/ctlseqs/ctlseqs.txt](url)

This allows mouse selection beyond column 223 in programs like vim.

Currently qtermwidget reports xterm version 115 for some reason.

```C++
void Vt102Emulation::reportSecondaryAttributes()
{
  // Seconday device attribute response (Request was: ^[[>0c or ^[[>c)
  if (getMode(MODE_Ansi))
    sendString("\033[>0;115;0c"); // Why 115?  ;)
  else
    sendString("\033/Z");         // FIXME I don't think VT52 knows about it but kept for
                                  // konsoles backward compatibility.
}
```

**Comment by yan12125** [comment]
Finished in https://github.com/lxde/qtermwidget/pull/166

> Currently qtermwidget reports xterm version 115 for some reason

I guess nobody uses that for feature detection. qtermwidget lacks some xterm features before 115 (e.g., recently added REP, and I believe there are more) and has some features for newer versions. Anyway the version number is meaningful for the actual xterm. If you find some useful feature in xterm but not in qtermwidget, feel free to open new issues.

**Comment by agaida** [comment]
@yan12125 - the 115 might be  the reason for some warnings about the terminal capabilities - will post these warnings here if they occour.

**Comment by yan12125** [comment]
Do you mean something like this?
```
Undecodable sequence: \001b(hex)[22;0;0t
Undecodable sequence: \001b(hex)[23;0;0t
```
(Running htop in qterminal, with ncurses 6.1)
