### ISSUE TITLE
Arrow keys don't work

### ISSUE THREAD

**Issue by LewisHein** [lxde/qtermwidget#103]
In the example program (or using QTermWidget in any application) the left, right, down and up arrows do nothing. This is quite limiting as it makes scrollback and command editing unavailable. 

I am compiling the latest release (0.7.0) against Qt 5.6 on Ubuntu 14.04

Note: I believe this has something to do with event filters, but I don't know enough Qt programming to fix it

**Comment by yan12125** [comment]
Arrow keys work fine for me. What's the output if you hit Ctrl+V first and then any arrow key? For example, Ctrl+V and then up shows ```^[OA```.

**Comment by LewisHein** [comment]
When I do this, I get nothing. Are you working on Mac OS by any chance? It seems to handle arrow key events differently than Linux (see [This StackOverflow question ](http://stackoverflow.com/questions/5987977/how-do-i-disable-qts-behavior-on-linux-of-capturing-arrow-keys-for-widget-focus)). 

Based on some quick grepping lib/TerminalDisplay.cpp seems to include event handling code to scroll the terminal with, among other things shift+up/down:  
`    
       
          // Keyboard-based navigation
          if ( event->modifiers() == Qt::ShiftModifier )
          {
          bool update = true;
  
          if ( event->key() == Qt::Key_PageUp )
          {
              _screenWindow->scrollBy( ScreenWindow::ScrollPages , -1 );
          }
          else if ( event->key() == Qt::Key_PageDown )
          {
              _screenWindow->scrollBy( ScreenWindow::ScrollPages , 1 );
          }
          else if ( event->key() == Qt::Key_Up )
          {
              _screenWindow->scrollBy( ScreenWindow::ScrollLines , -1 );
          }
          else if ( event->key() == Qt::Key_Down )
          {
              _screenWindow->scrollBy( ScreenWindow::ScrollLines , 1 );
          }
          else if ( event->key() == Qt::Key_End)
          {
              scrollToEnd();
          }
          else if ( event->key() == Qt::Key_Home)
          {
              _screenWindow->scrollTo(0);
          }
          else
              update = false;
  
          if ( update )
          {
              _screenWindow->setTrackOutput( _screenWindow->atEndOfOutput() );
  
              updateLineProperties();
              updateImage();
  
              // do not send key press to terminal
              emitKeyPressSignal = false;
          }
      }
`

I tried this and verified that shift+up arrow scrolls up., but I can't find any other similar code to handle other arrow key presses.

**Comment by yan12125** [comment]
I'm on Linux, too. Specifically, Qt 5.7.0 on Arch Linux.

I'll have to check more. Ironically arrow keys without any modifier (Ctrl/Alt/Shift) works fine on my machines, while Shift+Up and Shift+Down does not work. I guess my bug is related to yours and possibly the same.

**Comment by LewisHein** [comment]
OK, so my original hypothesis doesn't look so good. I wrote a primitive event filter for the example application that captures all events and sends all KeyEvents to the QTermWidget after printing "Yeah, that was a key press". If the event handler of the QTermWidget returned true, the filter prints "Event handled by the QTermWidget" But still, arrow keys without a shift modifier do nothing. (except print "Yeah, that was a key press") Oddly enough, with this event filter in place, the first key I press reports having been handled by the QTermWidget, but doesn't appear to do anything.

I have a gist here:

https://gist.github.com/LewisHein/106d97e21ca1ab6584abee2ffc761f54

**Comment by josefcibulka** [comment]
This looks more like a problem with keyboard layouts, defined in the files in the lib/kb-layouts directory.

I had the same problem (arrows had no effect, but Shift+Up/Down did scroll). In my case the problem was that I did an out-of-source build without installing, so qtermwidget did not find the kb-layouts directory. From get_kb_layout_dir() in tools.cpp I understand that it first looks to the installation path and if the directory is not there, it looks to a path under the directory where the executable is. But the kb-layouts directory is in the source tree only, so it is not found.

**Comment by DonnieWest** [comment]
Encountered the same issue. I've fixed it for my environment by [adding the escape codes to the default.keytab file](https://github.com/DonnieWest/qtermwidget/commit/a3c8ebe9c1987577f03015205e2b7fc05e94207a) 

Let me know if that fixes it for anyone else and I'll submit it as a PR
