### ISSUE TITLE
What TERM environment should be used?

### ISSUE THREAD

**Issue by singpolyma** [lxde/qtermwidget#12]
What should `TERM` be set to in order to get terminfo-based programs to work correctly with this?

**Comment by LeonardKoenig** [comment]
It seems that "default" (in Preferences->Behavior->Emulation) matches xterm (whatever colors; it just uses different keys), linux matches TERM=linux (obviously) and so on.
The description of "default" is "minimal featureset" which suggests that it *might* not be a complete xterm emulation.

**Comment by LeonardKoenig** [comment]
in konsole default is "xfree 4"

**Comment by LeonardKoenig** [comment]
I dont know why, but the XFree 4 configuration differentiates between shift+enter and enter, which some shells do not understand properly it seems (talking about zsh here).

**Comment by yan12125** [comment]
Currently I'm making qtermwidget behaving like xterm - adding missing features and fixing broken ones. I've opened https://github.com/lxde/qterminal/pull/401 to allow users to set $TERM and use xterm-256color as the default. xterm-direct, which indicates support for direct color mapping (24-bit true color), might be better, while it requires ncurses 6.1 and seems quite a few applications are broken with that.
