### ISSUE TITLE
Support Neovim's guicursor

### ISSUE THREAD

**Issue by yan12125** [lxde/qtermwidget#128]
Neovim's guicursor option supports Konsole, while it's not working in QTerminal. As there are quite a few terminal-specific codes in Neovim, more investigation is necessary to know whether it's a QTermWidget bug or Neovim's.

Ref: https://github.com/neovim/neovim/pull/3129

**Comment by DonnieWest** [comment]
@yan12125 my understanding is that guicursor simply sends the appropriate escape code to the terminal to be handled for changing the cursor shape. #112 adds those escape codes and #111 allows a consumer of QTermWidget to be aware when the profile has changed and the cursor shape needs to be updated.

Here's a short [example in python that should work with neovim](https://gist.github.com/DonnieWest/34144d3367287897f8d437b0e4fa8dda) however you _might_ need to have guicursor set in your init.vim to properly use it as they describe [here](https://github.com/neovim/neovim/wiki/Following-HEAD#20170402)

**Comment by yan12125** [comment]
Thanks! That's what I'm looking for. However, as a term widget, my first idea is that it can handle cursor changes by itself. (Maybe an option to turn this feature on/off) Konsole's design is kind of strange...

**Comment by DarkDefender** [comment]
Can any of you guys help me out and see it everything works as expected with:
https://github.com/neovim/neovim/issues/6997

**Comment by DonnieWest** [comment]
@DarkDefender I'll try to check it out in the next few days. I noticed that my colors were broken on Neovim HEAD and was sad :P

**Comment by DarkDefender** [comment]
@DonnieWest Yes, that is an other problem I've been trying to fix:
https://github.com/neovim/neovim/pull/7004

If you are talking about true color stuff that is.

**Comment by yan12125** [comment]
Okay. I got DECSCUSR handling fixed in qtermwidget's [handle-decscusr](https://github.com/lxde/qtermwidget/tree/handle-decscusr) branch. I can confirm cursor shapes doesn't work in authentic neovim 0.2.0 on Arch Linux while it works with https://github.com/DarkDefender/neovim/tree/cursor_shape. The cursor is a block in the normal mode and an I-beam in the insert mode. Great work @DarkDefender!

**Comment by DarkDefender** [comment]
BTW do you guys know if this has any chance to make it into upstream konsole?
It would be really nice if neovim didn't have do to agressive checks for if the user is using konsole.

We currently check for `KONSOLE_DBUS_SESSION` and `KONSOLE_PROFILE_NAME` env variables to see if we have to output konsole specific codes to change cursor. However this doesn't work nicely with tmux for example. So it would be nice if konsole could eventually support decscusr also.

**Comment by yan12125** [comment]
Dunno. If shouldn't be difficult but nobody works on it yet. I plan to backporting improvements in qtermwidget to konsole (https://github.com/lxde/qterminal/issues/320) but I haven't had so much time yet.

**Comment by DarkDefender** [comment]
Ah, I see. Thanks for explaining the situation for me. I wish you the best of luck in this matter!
