### ISSUE TITLE
Filter.cpp:421:35: error: 'class QStringList' 

### ISSUE THREAD

**Issue by ahuo002** [lxde/qtermwidget#129]
/home/github/qtermwidget/lib/Filter.cpp: In member function 'Konsole::UrlFilter::HotSpot::UrlType Konsole::UrlFilter::HotSpot::urlType() const':
/home/github/qtermwidget/lib/Filter.cpp:421:35: error: 'class QStringList' has no member named 'constFirst'
     QString url = capturedTexts().constFirst();

**Comment by yan12125** [comment]
According to https://doc.qt.io/qt-5/qlist.html#constFirst:

> This function was introduced in Qt 5.6.

Ping @luis-pereira (#122) Do you think it's good to use Qt 5.6 as a minimum or reverting #122 partially is better?

**Comment by yan12125** [comment]
@ahuo002: Which OS and version are you using?

**Comment by agaida** [comment]
there would be many points in the whole LXQt which would need if then - i'm not strictly against, but we should agree on that:
* 5.6.x is far outdated
* 5.7.1 is fine for now
* 5.8 isn't a good idea and finally
* 5.9 is the way to go until it is finally released

My 2¢

**Comment by luis-pereira** [comment]
5.6 is a sensible minimum IMO.

**Comment by agaida** [comment]
@luis-pereira - ok, we should check this again, not sure about 5.6 - it might be that we use some things that were introduced in 5.7 - but i really don't know by now.

**Comment by luis-pereira** [comment]
@agaida Qt 5.6.1 is enough.

**Comment by yan12125** [comment]
I merged #130. I'd like to hear feedback from @ahuo002 but seems he/she doesn't check Github notifications often. If this really brings trouble to users on old system, we can revisit it.

**Comment by luis-pereira** [comment]
@yan12125 I compiled both qterminal and qtermwidget with Qt 5.6.
