### ISSUE TITLE
cmake for qtermwidget is per build-arch

### ISSUE THREAD

**Issue by agaida** [lxde/qtermwidget#147]
so we should create and read the respective files with an architecture extension
##### Expected Behavior
dev-packages should be co-installable

##### Current Behavior
they are not, file conflicts

##### Possible Solution
add a architecture extension to the files in charge

##### Steps to Reproduce (for bugs)
see diff:  https://pb.5id.eu/CLvK

##### Context
```diff
--- i386/usr/share/cmake/qtermwidget5/qtermwidget5-config-version.cmake	2017-10-22 22:15:52.000000000 +0200
+++ amd64/usr/share/cmake/qtermwidget5/qtermwidget5-config-version.cmake	2017-10-22 22:15:52.000000000 +0200
@@ -19,13 +19,13 @@
 endif()
 
 # if the installed or the using project don't have CMAKE_SIZEOF_VOID_P set, ignore it:
-if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "4" STREQUAL "")
+if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
```
```diff
diff -u i386/usr/share/cmake/qtermwidget5/qtermwidget5-targets-relwithdebinfo.cmake amd64/usr/share/cmake/qtermwidget5/qtermwidget5-targets-relwithdebinfo.cmake
--- i386/usr/share/cmake/qtermwidget5/qtermwidget5-targets-relwithdebinfo.cmake	2017-10-22 22:15:52.000000000 +0200
+++ amd64/usr/share/cmake/qtermwidget5/qtermwidget5-targets-relwithdebinfo.cmake	2017-10-22 22:15:52.000000000 +0200
@@ -8,12 +8,12 @@
 # Import target "qtermwidget5" for configuration "RelWithDebInfo"
 set_property(TARGET qtermwidget5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
 set_target_properties(qtermwidget5 PROPERTIES
-  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/i386-linux-gnu/libqtermwidget5.so.0.8.0"
+  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib/x86_64-linux-gnu/libqtermwidget5.so.0.8.0"
```
This issue is somewhat important - without a change qtermwidget we can't put qtermwidget into sid - it will just not migrate anywhere: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880389

**Comment by agaida** [comment]
@yan12125 could you take care of that?

**Comment by agaida** [comment]
hmm - another point: is the bitness check really used and could we find the imports without hard writing the architecture into the text files - that would solve the problem too

**Comment by yan12125** [comment]
Does installing arch-specific files to /usr/lib fix it? Change ```${CMAKE_INSTALL_DATADIR}/cmake/``` to ```${CMAKE_INSTALL_LIBDIR}/cmake/``` in the following two lines: (not tested on Arch yet)

https://github.com/lxde/qtermwidget/blob/master/CMakeLists.txt#L226
https://github.com/lxde/qtermwidget/blob/master/CMakeLists.txt#L232

Ping @luis-pereira. A person knowing cmake should make things better.

> is the bitness check really used

Dunno. Those files are generated by CMake.

**Comment by agaida** [comment]
if cmake will find the files in the new location all things are fine i think - will test it

**Comment by yan12125** [comment]
I can test this on Arch later when I reach my development machine. Here's another thing - are other LXQt packages working fine on Debian? In /usr/share/cmake of my machine, there are quite a few arch-specific cmake files. Apparently those are created via similar approaches.
```
$ grep -r '${CMAKE_SIZEOF_VOID_P}' /usr/share/cmake
/usr/share/cmake/qt5xdgiconloader/qt5xdgiconloader-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/qt5xdg/qt5xdg-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/sysstat-qt5/sysstat-qt5-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/lxqt-globalkeys-ui/lxqt-globalkeys-ui-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/lxqt/lxqt-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/qtermwidget5/qtermwidget5-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/fm-qt/fm-qt-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
/usr/share/cmake/lxqt-globalkeys/lxqt-globalkeys-config-version.cmake:if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
```

**Comment by agaida** [comment]
good catch - btw, i must read more about it, right now i not fully understand the relevance of the bug. The only thing i understand is that it is not so nice - it has nearly no relevance for normal users. But it will bite you badly if you are a dev and play with multi-arch systems (not so unusual).

So right now i tend to be stubborn and only work on this reported bug :D - if it works out fine for us, we can change the other occurances and prevent some bug reports later.

**Comment by agaida** [comment]
Putting the files to libdir is not a good idea so far
```
CMake Error at /usr/share/cmake/qtermwidget5/qtermwidget5-config.cmake:19 (include):
  include could not find load file:
    /usr/share/cmake/qtermwidget5/qtermwidget5-targets.cmake
```

**Comment by agaida** [comment]
Some further informations - we are fine with moving the files to libdir, thats exactly what Qt does
```
qtdeclarative5-dev: /usr/lib/x86_64-linux-gnu/cmake/Qt5QuickWidgets/Qt5QuickWidgetsConfigVersion.cmake
qtkeychain-dev: /usr/lib/x86_64-linux-gnu/cmake/QtKeychain/QtKeychainConfig.cmake
```
