### ISSUE TITLE
make install does not create libqtermwidget4.so as as symlink to libqtermwidget4.so.0.6.0

### ISSUE THREAD

**Issue by YtvwlD** [lxde/qtermwidget#28]
If I run `make install` I get the file `/usr/local/lib/libqtermwidget4.so.0.6.0`.

But if I want to compile QTerminal, it won't link.

    /usr/bin/ld: cannot find -lqtermwidget4
    collect2: error: ld returned 1 exit status

If I create a symlink it works.

    $ cd /usr/lib/i386-linux-gnu
    $ ls
    > insgesamt 932
    > -rw-r--r-- 1 root root 945143 Nov  1 13:04 libqtermwidget4.so.0.6.0
    > drwxr-xr-x 2 root root   4096 Nov  1 13:17 pkgconfig/
    $ sudo ln -s libqtermwidget4.so.0.6.0  libqtermwidget4.so
    $ ls -l
    > insgesamt 932
    > lrwxrwxrwx 1 root root     24 Nov  1 14:15 libqtermwidget4.so -> libqtermwidget4.so.0.6.0
    > -rw-r--r-- 1 root root 945143 Nov  1 13:04 libqtermwidget4.so.0.6.0
    > drwxr-xr-x 2 root root   4096 Nov  1 13:17 pkgconfig/

**Comment by hykwok** [comment]
Here is the reference for building qtermwidget: 
http://www.linuxfromscratch.org/blfs/view/svn/lxqt/qtermwidget.html

**Comment by YtvwlD** [comment]
Umm, yes?

**Comment by agaida** [comment]
@YtvwlD - i guess this bug is a little bit outdated - if you agree we should close this one :)

**Comment by YtvwlD** [comment]
Well, yeah. Who uses Qt 4, anymore?
