### ISSUE TITLE
AnyMod + Page Up/Down not working

### ISSUE THREAD

**Issue by 3XX0** [lxde/qtermwidget#43]
Escape sequences involving `<Page-Up>` and `<Page-Down>` don't work.
Changing "Prior" to "PgUP" and "Next" to "PgDown" in the .keytab files fixes it.

See: http://lists.kde.org/?l=kde-commits&m=133523949610405

**Comment by LuxoftAKutsan** [comment]
Hi, I figured out, that PgUpand PgDown is now working as expected after commit 58c4da34ccf770a58d2baeb45d5149b67ca55676, but other controll keys as Delete or Up and Down Arrows are not working. Is is easy to solve, im am not shoure that it would be beautifil code, but it will be workable.

**Comment by yan12125** [comment]
Thanks to @DonnieWest, this is already fixed.
