### ISSUE TITLE
Fonts truncated vertically

### ISSUE THREAD

**Issue by saintdev** [lxde/qtermwidget#46]
Whenever I select a font it gets cut off vertically. Like the line the font is displayed on is not tall enough to display the font. Changing the font size does not help, the font still gets cut off in the same place, it is just smaller. The attached screenshot shows two terminals with Adobe's Source Code Pro on the left and Oxygen Mono on the right both 10 pt.

![nt8nlwt](https://cloud.githubusercontent.com/assets/678111/6994942/8667d7ae-dae8-11e4-983e-8cb73d9829fd.png)

**Comment by johnnycooper** [comment]
I've got the same bug.

**Comment by LeonardKoenig** [comment]
same

**Comment by guzt** [comment]
This was happening to me as well, running qtermwidget and qterminal at HEAD from today on arch with monospaced fonts from ttf-google-fonts-git. This fixes it for me. I haven't used Qt much so can't really say why bottom align doesn't work well for me in this case.

```
diff --git a/lib/TerminalDisplay.cpp b/lib/TerminalDisplay.cpp
index c524802..0ef17a5 100644
--- a/lib/TerminalDisplay.cpp
+++ b/lib/TerminalDisplay.cpp
@@ -732,7 +732,7 @@ void TerminalDisplay::drawCharacters(QPainter& painter,
         if (_bidiEnabled)
             painter.drawText(rect,0,text);
         else
-            painter.drawText(rect, Qt::AlignBottom, LTR_OVERRIDE_CHAR + text);
+            painter.drawText(rect, Qt::AlignCenter, LTR_OVERRIDE_CHAR + text);
     }
 }
 
```

**Comment by mato7d5** [comment]
I've same problem on Arch Linux. This patch works for me:
`diff --git a/lib/TerminalDisplay.cpp b/lib/TerminalDisplay.cpp
index c524802..0534f55 100644
--- a/lib/TerminalDisplay.cpp
+++ b/lib/TerminalDisplay.cpp
@@ -732,7 +732,7 @@ void TerminalDisplay::drawCharacters(QPainter& painter,
         if (_bidiEnabled)
             painter.drawText(rect,0,text);
         else
-            painter.drawText(rect, Qt::AlignBottom, LTR_OVERRIDE_CHAR + text);
+            painter.drawText(rect, Qt::AlignBottom, text);
     }
 }
`
