### ISSUE TITLE
Should support "bracketed paste mode"

### ISSUE THREAD

**Issue by hagabaka** [lxde/qtermwidget#48]
[Bracketed paste](https://cirw.in/blog/bracketed-paste) allows programs running in the terminal to tell whether text was typed or pasted, so that they can handle it more intelligently, for example with plugins zsh can defer running commands by line, and vim can turn off autoindent while pasting.

QTerminal doesn't seem to support this, as the above-mentioned plugins work for xterm but not QTerminal.

~~I think this can be implemented by editing [`TerminalDisplay::emitSelection`](https://github.com/qterminal/qtermwidget/blob/master/lib/TerminalDisplay.cpp#L2503).~~

It looks like this was implemented in [konsole git](https://quickgit.kde.org/?p=konsole.git&a=commit&h=886f12d730e0678bb193827a75074f178a8e8d62) in Janurary 2014.

**Comment by f2404** [comment]
@hagabaka Could you validate the implementation please?
