### ISSUE TITLE
qtermwidget: FTBFS on kFreeBSD: 'TCGETS' not declared

### ISSUE THREAD

**Issue by agaida** [lxde/qtermwidget#50]
Dunno nothing about *BSD, but the rest of qtermwidget compile fine on Debian/kfreeBSD. The proposed fix don't work, if i can help, i will, but i have no clue
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798053

**Comment by pinotree** [comment]
All the `lib/kpty*` sources are direct copies from the `kpty` framework developed by the KDE project (see https://projects.kde.org/projects/frameworks/kpty). A solution here would be allow to build against an external `kpty` framework (which is stable, keeps source and binary compatibility, and should be of no concern).

Anyway, if you still want to keep using the embedded copy, the better fix for this issue is what I did in `kpty` few months ago:
https://quickgit.kde.org/?p=kpty.git&a=commitdiff&h=35ea45b588db9afcbd796576833ac338c6b4b8e8
(but please notice the cost of embedded copies -- double the fix in what is already a shared code (library) :-( )

**Comment by agaida** [comment]
sounds good :)

**Comment by jleclanche** [comment]
kpty brings in some useless stuff like ki18n...

**Comment by jleclanche** [comment]
@pinotree ki18n can be removed, there's no actual po files to install... despite all the error strings being i18n'd. Could you do it or do I need to send a patch? (I'd rather not)

**Comment by pinotree** [comment]
The .po files for kpty are among the other translation files in the KDE SVN repo, and added in the repository at release time (see the content of tags).

Also, the fact that kpty uses ki18n is an internal detail, you won't end up using ki18n yourself (and btw, ki18n is a much better framework than what is being provided in Qt itself).

**Comment by jleclanche** [comment]
@pinotree It's an additional dependency to the dependency list when installing it... and small as it may be, our users care about these dep lists :/

It also pulls it kcoreaddons (which we depended on in 0.9 but dropped in 0.10) and gamin, not sure why.

**Comment by jleclanche** [comment]
We can evaluate whether we'll ourselves move to ki18n when we take care of our own translation system. I'll consider it but I have to look into how it works first.

**Comment by pinotree** [comment]
Most of the size taken by ki18n is its translations and data, not much the library itself.
kpty uses kcoreaddons for the `KUser` class.
`KDirWatch` in kcoreaddons can optionally use gamin (or fam) for file monitoring.

**Comment by jleclanche** [comment]
@pinotree so gamin is an optional runtime dep?

In any case, I don't think we can justify pulling in ki18n and I don't see why kpty pulls it in merely for error strings when they're not meant to be translated. Is this something you're willing to drop?

**Comment by pinotree** [comment]
gamin has a library (rather small) which kcoreaddons links to if enabled at build time, and a runtime daemon which does the actual monitoring job: initializing gamin without it will fail, but `KDirWatch` will just skip it. In any case, inotify is the preferred file watching method for local filesystems on Linux; non-local filesystems (hello NFS) and other UNIX systems have fam/gamin as preferred method, falling back to polling.

Error strings from `QIODevice` and subclasses are translated, even those in Qt itself.
Also, I'm not the actual maintainer of kpty, you would need to contact people at the kde-frameworks-devel [1] mailing list.

[1] https://mail.kde.org/mailman/listinfo/kde-frameworks-devel

**Comment by jleclanche** [comment]
@agaida Can you take care of this? I'm not really available this week.

**Comment by pinotree** [comment]
Me neither, sorry :-/
But then, as a long-time KDE translator, I don't see a particular problem with ki18n, especially when it is miles better as translation system than Qt's. Hence I would not be the best person to vouch for not using it.

**Comment by jleclanche** [comment]
@pinotree Was asking agaida, np ;) 

On ki18n, we're planning to solve our translation issues without extra libraries and reuse the Qt system. I'm all ears if you'd like to try and sell me on ki18n though.

**Comment by agaida** [comment]
@paulolieuthier: Works so far, thank you very much - have to pack this proper and build  this in a clean environment, until now qterminal and qtermwidget only run as root - i think install it to usr/local/bin wasn't the best of all ideas - but this doesn't matter so far, it was only cmake, make, make install without setting any prefix. Great work.

**Comment by paulolieuthier** [comment]
Great. I'll file the PR.

**Comment by agaida** [comment]
@paulolieuthier: hi, i made a regular package with your fixe, it solve the FTBFS but works not 100%. The widget is built without errors, the qterminal build and run just fine - but only as root.
As root i geth this output: <pre>
~# qterminal
TRANSLATIONS_DIR: Loading translation file "qterminal_de_DE.qm" from dir /usr/share/qterminal/translations
load success: true
Properties constructor called
Canot open file "/root/.config/qterminal.org/qterminal_bookmarks.xml"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x6c1ba0, name = "TermWidget_1") emulation: "default"
Session::run() - program: "/bin/bash"
Session::run() - arguments: ("")
started!
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x6c1ba0, name = "TermWidget_1") emulation: "default"
QObject::connect: No such slot TabWidget::renameSession()
QObject::connect:  (receiver name: 'consoleTabulator')
-----
some times later if i close the root terminal
-----
QProcess: Destroyed while process ("/bin/bash") is still running.</pre>

As user i get this output: <pre>
$ qterminal
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
TRANSLATIONS_DIR: Loading translation file "qterminal_de_DE.qm" from dir /usr/share/qterminal/translations
load success: true
Properties constructor called
Canot open file "/home/agaida/.config/qterminal.org/qterminal_bookmarks.xml"
Canot open file "/home/agaida/.config/qterminal.org/qterminal_bookmarks.xml"
Can't open slave pseudo teletype
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x8c2d70, name = "TermWidget_1") emulation: "default"
Session::run() - program: "/bin/bash"
Session::run() - arguments: ("")
Unable to set terminal attributes.
started!
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x8c2d70, name = "TermWidget_1") emulation: "default"
QObject::connect: No such slot TabWidget::renameSession()
QObject::connect:  (receiver name: 'consoleTabulator')
-- i close the terminal --
QProcess: Destroyed while process ("/bin/bash") is still running.</pre>

Sorry it took so long, i had to install a full kfreebsd dev environment on a real iron.
