### ISSUE TITLE
qterminial does not open on Ubuntu

### ISSUE THREAD

**Issue by rohshall** [lxde/qtermwidget#62]
When I open qterminal, the whole screen blanks out. When I click anywhere except in the area where the qterminal window is supposed to be (top left), only then I can get my desktop back. Anytime I try to  click inside qterminal window, the whole desktop goes blank again. I have to close qterminal using my window manager. 

I am using lxqt on Ubuntu xenial.

```
 ~ % uname -a
Linux linux-swadnerkar 4.4.0-6-generic #21-Ubuntu SMP Tue Feb 16 20:32:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 ~ % cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu Xenial Xerus (development branch)"

 ~ % qterminal -version
Gtk-Message: Failed to load module "overlay-scrollbar"
Xlib:  extension "RANDR" missing on display ":0".
0.6.0

 ~ % ldd /usr/bin/qterminal 
	linux-vdso.so.1 =>  (0x00007ffc09bfe000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f3bae167000)
	libqtermwidget5.so.0 => /usr/lib/x86_64-linux-gnu/libqtermwidget5.so.0 (0x00007f3baded4000)
	libQt5X11Extras.so.5 => /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so.5 (0x00007f3badece000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f3badb94000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f3bad64c000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f3bad175000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3bacdf3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3bacbdd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3bac812000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3bac5f4000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f3bac3a1000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f3bac08f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3babd87000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f3babb64000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3bab960000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f3bab73b000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f3bab4dd000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3bab2c2000)
	libGL.so.1 => /usr/lib/nvidia-352/libGL.so.1 (0x00007f3baaf92000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f3baab30000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f3baa79b000)
	libpcre16.so.3 => /usr/lib/x86_64-linux-gnu/libpcre16.so.3 (0x00007f3baa535000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3baa32d000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563538f9c000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f3baa124000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f3ba9eb4000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f3ba9caf000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f3ba9aa9000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f3ba97ff000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f3ba95e2000)
	libnvidia-tls.so.352.63 => /usr/lib/nvidia-352/tls/libnvidia-tls.so.352.63 (0x00007f3ba93df000)
	libnvidia-glcore.so.352.63 => /usr/lib/nvidia-352/libnvidia-glcore.so.352.63 (0x00007f3ba694c000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f3ba6739000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f3ba4c82000)
```

These are the console logs when I start qterminal:
```
Gtk-Message: Failed to load module "overlay-scrollbar"
Xlib:  extension "RANDR" missing on display ":0".
TRANSLATIONS_DIR: Loading translation file "qterminal_en.qm" from dir /usr/share/qterminal/translations
load success: false
Properties constructor called
QDir::exists: Empty or null file name
Canot open file "/home/swadnerkar/.config/qterminal.org/qterminal_bookmarks.xml"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x1f9dfd0, name = "TermWidget_1") emulation: "default"
Session::run() - program: "/bin/zsh"
Session::run() - arguments: ("")
started!
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x1f9dfd0, name = "TermWidget_1") emulation: "default"
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x1f9dfd0, name = "TermWidget_1") emulation: "default"


```

**Comment by agaida** [comment]
the output of **apt-cache policy qterminal** would be helpful

**Comment by rohshall** [comment]
Thanks for your quick response. Here it is:

```
 ~/remilon/sites-study-com (git)-[master]- % apt-cache policy qterminal
qterminal:
  Installed: 0.6.0+20150802-2
  Candidate: 0.6.0+20150802-2
  Version table:
 *** 0.6.0+20150802-2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by f2404** [comment]
These two message look suspicious. Do they appear when running other apps?
```
Gtk-Message: Failed to load module "overlay-scrollbar"
Xlib:  extension "RANDR" missing on display ":0".
```

**Comment by rohshall** [comment]
Yes, they appear while running most other applications on my machine.
For example, when I run my browser from command line, I get this:
Gtk-Message: Failed to load module "overlay-scrollbar"
Xlib:  extension "RANDR" missing on display ":0".

**Comment by f2404** [comment]
This is interesting. What DE or WM are you using?

**Comment by rohshall** [comment]
I am using LxQt version 0.10.0
The RANDR error I get in all DEs though. LxQt and Xfce are the DEs that
work without any problem with the NVidia driver (proprietory driver) on my
machine.

**Comment by rohshall** [comment]
After installing some package called overlay-scrollbar-gtk2, the scollbar
error went away. It seems that the XRandr warning is harmless and people
with NVidia cards with Xinerama enabled have been getting this error since
Ubuntu 11.04. (http://ubuntuforums.org/showthread.php?t=963878) As far as I
can tell (and also from the comments in the post, it does not seem to
affect the working)

**Comment by agaida** [comment]
i suggest to do nothing and don't spend any time on this issue - please use the current souces, if that is not possible, ask the ubuntu repo maintainers to catch up with their version of qterminal and qtermwidget. New and improved packages are already in sid and testing so this should be possible.

@jleclanche @pcman @pvanek - we should make a regular release as soon of both packages as possible, the packages in the repos are only snapshots of the ongoing development.

**Comment by rohshall** [comment]
I already source compiled both qtermwidget and qterminal from the latest
master from github repo and the problem is still there. That is why I
opened this issue. (I mentioned this in my second or third comment, I
think. Maybe I should have put it in the first post.)

**Comment by agaida** [comment]
it seems to be a downstream problem - really. And only a wild guess: Tried to clean up the configuration files?

**Comment by rohshall** [comment]
Yes, I did rm -fr ~/.config/qterminal.org before starting qterminal. Thanks.

**Comment by agaida** [comment]
it might be interesting - one could get the latests snapshot here: 
http://anonscm.debian.org/cgit/pkg-lxqt/qtermwidget.git/?h=lxqt-snapshots/latest
https://anonscm.debian.org/git/pkg-lxqt/qterminal.git?h=lxqt-snapshots/latest
and build the packages local with debuild - if the debugging symbols are installed, running qterminal in gdb might be a good idea and could give an idea whats wrong - the listed dependencies should be fullfillable with ubuntu 16.04. 

I'm running out of ideas, i use qterminal since over two years as a daily driver with sid.

**Comment by rohshall** [comment]
Sorry, how do I download the snapshot from there? Clicking on links takes
me to commit messages instead of tar.gz files.

**Comment by agaida** [comment]
apt install debhelpers devscripts git
git clone $foo
cd foo
apt build-dep $foo
debuild 
cd ..
debi *changes

done

**Comment by rohshall** [comment]
Sorry for asking stupid question. But, git clone and debuild does not seem
to work well together. debuild expects some .tar.xz files to be present
(which apt-get source downloads)
These are the steps I followed:

 ~/temp % git clone https://anonscm.debian.org/git/pkg-lxqt/qtermwidget.git
Cloning into 'qtermwidget'...
remote: Counting objects: 574, done.
remote: Compressing objects: 100% (372/372), done.
remote: Total 574 (delta 292), reused 390 (delta 171)
Receiving objects: 100% (574/574), 354.89 KiB | 313.00 KiB/s, done.
Resolving deltas: 100% (292/292), done.
Checking connectivity... done.

 ~/temp % cd qtermwidget
 ~/temp/qtermwidget (git)-[debian/sid]- % apt build-dep qtermwidget
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission
denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you
root?

 ~/temp/qtermwidget (git)-[debian/sid]- % sudo apt build-dep qtermwidget
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 ~/temp/qtermwidget (git)-[debian/sid]- % debuild
This package has a Debian revision number but there does not seem to be
an appropriate original tar file or .orig directory in the parent directory;
(expected one of qtermwidget_0.6.0+20160108.orig.tar.gz,
qtermwidget_0.6.0+20160108.orig.tar.bz2,
qtermwidget_0.6.0+20160108.orig.tar.lzma,
 qtermwidget_0.6.0+20160108.orig.tar.xz or qtermwidget.orig)
continue anyway? (y/n)

**Comment by rohshall** [comment]
If I compile the sources from this repo using the cmake and make, I get the
same issue.

**Comment by agaida** [comment]
a) learn to use proper tools
b) i'm closing this now, it's a non issue.

Feel free to provide informations regarding this issue in launchpad, it's all but not a upstream issue.
I don't want to be harsh, but have a look at this: http://i.imgur.com/SVWCgsN.png

**Comment by wxl** [comment]
I know this is closed, but I wanted to confirm I do not have this problem, either. I'm running Lubuntu with the same `qterminal` version. Admittedly, it's on the 4.3.0-5-generic kernel (need to update this VM), but that's unlikely the issue. My output does not include:
   
    Gtk-Message: Failed to load module "overlay-scrollbar"
    Xlib:  extension "RANDR" missing on display ":0".

**Comment by rohshall** [comment]
It is OK if this is a rare problem and qterminal team is not interested in
solving this. But, I don't think "learn to use proper tools" is a reason
for this because being able to make a debian package out of a git repo
snapshot is not a requirement to use qterminal.

On Tue, Feb 23, 2016 at 5:09 PM, Walter Lapchynski <notifications@github.com

**Comment by agaida** [comment]
at least one should checkout the right branch lxqt-snapshots/latest - and use the prefered tool for local builds in debian and debian-derivatives: debuild or dpkg-buildpackage, as it use the debian/rules in the package. only a hint

**Comment by wxl** [comment]
Even outside of the whole tools thing, I have more or less the exact same situation you have (except for the kernel) and I cannot replicate it. Bugs that can't be replicated are almost impossible to fix. 

I suspect the issue somehow relates to a graphics issue, as I don't have a proprietary driver in use.
