### ISSUE TITLE
How to send Ctrl+c via object method

### ISSUE THREAD

**Issue by Levi-Armstrong** [lxde/qtermwidget#63]
Is there a method to send the equivalent to Ctrl+c to the QTermWidget object? I would like to have a stop button on the GUI to perform the same as Ctrl+c.

**Comment by f2404** [comment]
I'm afraid I don't understand what you want to achieve here...

**Comment by Levi-Armstrong** [comment]
I have the QTermWidget integrated into my GUI and say the user starts a program via command line within QTermWidget for example: Blender. So one way to close Blender is through Blender itself or another way is from within the terminal by pressing Ctrl+c which sends a SIGINT (interrupt) signal to the process. I am looking for a way to send the SIGINT signal by means of the QTermWidget to allow for me to integrate a stop button. I have tried the sendText method but it appears to not have any effect while there is an active process.

**Comment by Levi-Armstrong** [comment]
I was able to implement a solution by looping through all of the childern of the QTermWidget until I found the Konsole::TerminalDisplay object and send a keyEvent. 

```
foreach(QObject *obj, m_tabWidget->currentWidget()->children())
  {
    if(QLatin1String(obj->metaObject()->className()) == QLatin1String("Konsole::TerminalDisplay"))
    {
      QKeyEvent *event1 = new QKeyEvent(QEvent::KeyPress, Qt::Key_C, Qt::ControlModifier);
      QCoreApplication::postEvent(obj, event1);

      QKeyEvent *event2 = new QKeyEvent(QEvent::KeyRelease, Qt::Key_C, Qt::ControlModifier);
      QCoreApplication::postEvent(obj, event2);
      break;
    }
  }
```

**Comment by f2404** [comment]
I see your point now, thanks.

I'd suggest you to look into qterminal code (https://github.com/lxde/qterminal), starting with termwidget.cpp - I don't see it doing anything special to pass keypresses to QTermWidget.

**Comment by Levi-Armstrong** [comment]
@f2404, Thank you for your help, I am looking into you suggestion.

**Comment by f2404** [comment]
@Levi-Armstrong Actually, I have deleted my comment since I don't think it's really relevant.
But I would be glad if you could find any help within `qterminal` sources.
