### ISSUE TITLE
Path of build directory gets incorporated in shared library

### ISSUE THREAD

**Issue by pmattern** [lxde/qtermwidget#70]
The path of the directory were QTermWidget was built gets incorporated in the shared library `libqtermwidget5.so.0.6.0`.

E. g. when directories `/usr/local/u93ght/{build,qtermwidget,installation}` are used as build directory, the one comprising the sources and dummy target directory there's
```
$ strings /usr/local/u93ght/installation/usr/local/lib64/libqtermwidget5.so.0.6.0 | grep u93ght 
/usr/local/u93ght/qtermwidget/lib/BlockArray.cpp
/usr/local/u93ght/qtermwidget/lib/History.cpp
/usr/local/u93ght/qtermwidget/lib/Screen.cpp
/usr/local/u93ght/qtermwidget/lib/Session.cpp
```

So far I couldn't see any real malfunction associated with this problem, but only messages like
> Mai 12 10:54:36 arch-64-lxqt-git qterminal[1039]: /usr/local/peter/yaourt-tmp-peter/aur-qtermwidget-git/src/qtermwidget/lib/Session.cpp 346 : setting background colour to  "?"

in systemd's journal where the path represents the one used by a script invoking `yaourt` on my production system.
These belong to QTerminal the binary `qterminal` of which is affected as well. Cannot tell whether this is due to a problem on its own or secondary due to the one in QTermWidget as the latter seems to be rather long-standing.

Seen compiling d572f39 on Arch Linux.

**Comment by f2404** [comment]
@pmattern Does the patch resolve this for you?

**Comment by pmattern** [comment]
I cannot see the problem any longer using your branch `70_assert`, either itself or rebased against current master.

**Comment by f2404** [comment]
Okay, thanks.
I've rebased it against the master, btw.
