### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by yan12125** [lxde/qtermwidget#88]
I love this feature, which is available in xfce4-terminal.

My try: Seems Qt allows setting a background image for QWidget via setBrush. However, I haven't made it work yet.

``` Diff
diff --git a/lib/TerminalDisplay.cpp b/lib/TerminalDisplay.cpp
index c524802..a8f75ea 100644
--- a/lib/TerminalDisplay.cpp
+++ b/lib/TerminalDisplay.cpp
@@ -155,7 +155,8 @@ void TerminalDisplay::setBackgroundColor(const QColor& color)
 {
     _colorTable[DEFAULT_BACK_COLOR].color = color;
     QPalette p = palette();
-      p.setColor( backgroundRole(), color );
+      // p.setColor( backgroundRole(), color );
+      p.setBrush(QPalette::Base, QPixmap("/home/yen/Pictures/wallpaper/iE4sA6MoGncOz.jpg"));
       setPalette( p );

       // Avoid propagating the palette change to the scroll bar

```

**Comment by f2404** [comment]
Unfortunately, you should have meant "which **was** available xfce4-terminal".
Background image support has been removed from vte, and I haven't found a way how to bypass vte here yet (though there are some ideas).

**Comment by yan12125** [comment]
You're right. On Arch Linux the latest xfce4-terminal (0.6.3) is still built upon vte 0.28.2-8.

Seems qtermwidget is not using vte? ```grep -ir vte``` in this repository yields nothing.

**Comment by f2404** [comment]
> You're right. On Arch Linux the latest xfce4-terminal (0.6.3) is still built upon vte 0.28.2-8.

There's version 0.6.90 unofficially available which builds against vte3 and gtk3. This version does not support background images, and I need to find a way how to bring this feature back in, without support from vte.

> Seems qtermwidget is not using vte? grep -ir vte in this repository yields nothing.

No, vte is a gtk terminal widget while qterminal is a qt app using qtermwidget.

Actually, all vte-related stuff is kind of off-topic here; I just wanted to give you heads-up regarding xfce4-terminal and background images.

**Comment by yan12125** [comment]
Hmm, seems I've misunderstood you or vice versa. I've switched to qterminal from xfce-terminal, and I hope qterminal can have background images, like (old) xfce4-terminal.

**Comment by yan12125** [comment]
xfce4-terminal 0.8 is released yesterday. It switches to GTK+3 and VTE3, while background image support is re-implemented outside VTE. It draws the image under the VTE widget and set the transparency of VTE. I guess QTermWidget or QTerminal can do something similar.

References: https://bugzilla.xfce.org/show_bug.cgi?id=12845

**Comment by yan12125** [comment]
I got background images partially working. The background image is not re-painted correctly when scrolling.
```Diff
diff --git a/lib/TerminalDisplay.cpp b/lib/TerminalDisplay.cpp
index aeebc7e..073fb62 100644
--- a/lib/TerminalDisplay.cpp
+++ b/lib/TerminalDisplay.cpp
@@ -615,7 +615,7 @@ void TerminalDisplay::drawBackground(QPainter& painter, const QRect& rect, const
 
             painter.save();
             painter.setCompositionMode(QPainter::CompositionMode_Source);
-            painter.fillRect(contentsRect, color);
+            // painter.fillRect(contentsRect, color);
             painter.restore();
         }
         else
@@ -1225,6 +1225,10 @@ void TerminalDisplay::paintEvent( QPaintEvent* pe )
 {
   QPainter paint(this);
 
+
+  paint.drawPixmap(0, 0, QPixmap("/path/to/image.jpg"));
+  paint.fillRect(contentsRect(), QColor(0, 0, 0, 192));
+
   foreach (const QRect &rect, (pe->region() & contentsRect()).rects())
   {
     drawBackground(paint,rect,palette().background().color(),
```

**Comment by yan12125** [comment]
Closing as #95 and lxde/qterminal#273 landed
